---
version: 2

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2

    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache

    - run:
        name: Get test data
        command: |
          if [[ ! -d ~/data/mrtrix3_connectome_data ]]; then
            wget -c -P ${HOME}/downloads/ "https://dl.dropboxusercontent.com/u/8970757/mrtrix3_connectome_data.tar" \
            && mkdir -p ${HOME}/data && tar xf ${HOME}/downloads/mrtrix3_connectome_data.tar -C ${HOME}/data;
          fi
    - run:
        name: Build Docker image
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
          bash build_docker.sh  

    - save_cache:
        key: my_cache
        paths:
        - ~/docker
        - ~/data

    - persist_to_workspace:
        root: /home/circleci
        paths:
        - docker/image.tar

  test:
    docker:
    - image: ubuntu-2204:2022.10.2

    steps:
    - attach_workspace:
        at: /tmp/workspace

    - run: docker load -i /tmp/workspace/image.tar

    - run: mkdir -p ${HOME}/outputs

    - run:
        name: Print version
        command: |
          docker run -ti --rm --read-only \
            -v /tmp:/tmp \
            -v /var/tmp:/var/tmp \
            /tmp/workspace/data/ds114_test1:/bids_dataset \
              bids/${CIRCLE_PROJECT_REPONAME,,} --version

    - run:
        name: Print version
        command: |
          docker run -ti --rm --read-only \
            -v /tmp:/tmp \
            -v /var/tmp:/var/tmp \
            /tmp/workspace/data/mrtrix3_connectome_data:/bids_dataset \
            -v ${HOME}/outputs1:/outputs
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs \
                participant1 \
                --participant_label 01 --n_cpus 2
        no_output_timeout: 6h
    - run:
        name: Print version
        command: |
          docker run -ti --rm --read-only \
            -v /tmp:/tmp \
            -v /var/tmp:/var/tmp \
            /tmp/workspace/data/mrtrix3_connectome_data:/bids_dataset \
            -v ${HOME}/outputs1:/outputs
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs \
                participant1 \
                --participant_label 02 --n_cpus 2
        no_output_timeout: 6h

    - store_artifacts:
        path: ~/output

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar
    - run:
        name: push to dockerhub
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
          bash push_docker.sh  

workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - test:
        requires:
        - build
        filters:
          tags:
            only: /.*/
    - deployment:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/

# VS Code Extension Version: 1.5.1
